name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'
jobs:
  check-lock-file-version:
    name: NPM Lock File Version
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check NPM lock file version
        uses: mansona/npm-lockfile-version@v1
        with:
          version: 1
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Node 12
            NODE_VERSION: 12
          - name: Node 14
            NODE_VERSION: 14
          - name: Node 16
            NODE_VERSION: 16
          - name: Node 18
            NODE_VERSION: 18
    timeout-minutes: 30
    env:      
      NODE_VERSION: ${{ matrix.NODE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.NODE_VERSION }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.NODE_VERSION }}-
      - run: npm ci
      - run: npm run test
