name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'
jobs:
  check-lock-file-version:
    name: NPM Lock File Version
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check NPM lock file version
        uses: mansona/npm-lockfile-version@v1
        with:
          version: 1
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '15', '16', '17', '18' ]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run test
